### PR TITLE
[Merged by Bors] - Fix pbr shader compiliation error, `#version` has to be in the first line

### PR DESCRIPTION
**Pull request by Philipp-M**
I've had problems with compiling and running the pbr example:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Compilation("glslang_shader_preprocess:\nInfo log:\nERROR: 0:40: \'#version\' : must occur first in shader \nERROR: 0:40: \'#version\' : bad profile name; use es, core, or compatibility \nERROR: 0:40: \'#version\' : bad tokens following profile -- expected newline \nERROR: 3 compilation errors.  No code generated.\n\n\nDebug log:\n\n")', crates/bevy_render/src/pipeline/pipeline_compiler.rs:161:22
```

I've checked each shader, and only one shader hasn't had `#version` in the first line.

This change fixed my issue.

### CODE REVIEW

**Comment by mockersf** [comment]
from https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)#Version
> The #version directive must appear before anything else in a shader, save for whitespace and comments. If a #version directive does not appear at the top, then it assumes 1.10, which is almost certainly not what you want.

so it should still work, strange that's an issue in your case?

anyway, doesn't hurt to have it first

**Review by mockersf — APPROVED** [review]

**Review by jamadazi — APPROVED** [review]
