### ISSUE TITLE
bevy_math fails to compile without default features

### ISSUE THREAD

**Issue by ElliottjPierce** [bevyengine/bevy#18775]
## Info

Bevy version: 0.16.0-rc.3
rust/cargo version: cargo 1.86.0 (adf9b6ad1 2025-02-28)
Os: MacOs 15.3.2

## What you did

Add to Cargo.toml

`bevy_math = {version = "0.16.0-rc.3", default-features = false}`

## What went wrong

Fails to build.

There are 418 errors of the type "cannot find function `atan2` in module `math`". It's not just `atan2`.

## Workaround

Enabling default features works fine. (Because "std" is default.)

Although it is not currently documented, this can be fixed by enabling `bevy_math` feature `std`, `libm`, or `nostd-libm`.

## Cause

Fails to build with `glam = { version = "0.29.3", default-features = false, features = ["bytemuck"] }` in Cargo.toml, which is the same dependency as in bevy_math's cargo file.

## Proposed solution

Upgrading to `glam = { version = "0.30.1", default-features = false, features = ["bytemuck"] }` provides the more graceful error message: "You must specify a math backend. Consider enabling either `std`, `libm`, or `nostd-libm`."

Sure enough `glam = { version = "0.30.1", default-features = false, features = ["bytemuck", "nostd-libm"] }` compiles fine.

I believe upgrading to "0.30.1" will fix the issue, and we'll need a migration guide to tell users to enable a bevy_math feature "`std`, `libm`, or `nostd-libm`" that forwards to glam.

**Comment by ElliottjPierce** [comment]
So upgrading actually won't work. `encase` uses version 29, so if we upgrade, everything breaks. `hexasphere` also depends on version 29, but I think that can be upgraded.

**Comment by ElliottjPierce** [comment]
Use the workaround for now until we can do #18776.
