### ISSUE TITLE
Local CI (`cargo r -p ci`) fails because it seems to run docs in stable but uses attributes of nightly:

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#16871]
Note that local CI (`cargo r -p ci`) still fails because it seems to run docs in stable but uses attributes of nightly:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src\lib.rs:2:21
  |
2 | #![cfg_attr(docsrs, feature(doc_auto_cfg))]
  |   
```

_Originally posted by @djeedai in https://github.com/bevyengine/bevy/issues/16862#issuecomment-2549726848_

**Comment by mockersf** [comment]
caused by https://github.com/bevyengine/bevy/pull/16147, as I warned

**Comment by alice-i-cecile** [comment]
https://github.com/bevyengine/bevy/pull/15387 is the ultimate cause of our nightly docs requirements; let me look into this.

**Comment by mockersf** [comment]
all nightly needs are behind a feature, #16147 enabled that feature when checking docs. it should enable it only when a nightly is detected
