### PR TITLE
[Merged by Bors] - Fix PBR regression for unlit materials 

### LINKED ISSUE #2190: Unlit materials cause shader panic
## Bevy version

Commit e3435e5

**Confirmed the breaking change happened in 73f4a9d18f609e52d28e2963635560e0b78a2f9f**
## Operating system & version

Windows 10

## What you did

Existing plugins that use unlit materials now panic as soon as meshes with that material are shown. Results in the following panic:

```shell
thread 'main' panicked at 'Shader compilation error:
glslang_shader_parse:
Info log:
ERROR: 0:293: 'getDistanceAttenuation' : no matching overloaded function found
ERROR: 0:293: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.
```

Lines in question appear to be in the pbr frag shader here:

https://github.com/bevyengine/bevy/blob/73f4a9d18f609e52d28e2963635560e0b78a2f9f/crates/bevy_pbr/src/render_graph/pbr_pipeline/pbr.frag#L291-L292

### PR DESCRIPTION
**Pull request by aevyrie**
Fixes the frag shader for unlit materials by correcting the scope of the `#ifndef` to include the light functions. Closes #2190, introduced in #2112.

Tested by changing materials in the the `3d_scene` example to be unlit. Unsure how to prevent future regressions without creating a test case scene that will catch these runtime panics.

### CODE REVIEW

**Review by mockersf — APPROVED** [review]

**Comment by mtsr** [comment]
Please add an unlit material to one of the examples, to help us catch this in the future.

**Comment by aevyrie** [comment]
Added a test to the pbr example, seeing as the pbr shader file held the regression. Bumped up the spheres a row, and improved the camera and lighting while I was at it, to remove projection distortion and varying light direction.

image
