### ISSUE TITLE
Linux WebGL2 Chromium example runner job fails due to "Shader Compilation failed"

### ISSUE THREAD

**Issue by kfc35** [bevyengine/bevy#24163]
## Bevy version and features

Main 4bd3708d523b6ec00e40c798c7f4e77dbd1c1788

## \[Optional\] Relevant system information

Pixel Eagle’s `linux` `webgl2` `chromium` job specs

(note that the `linux` `webgl2` `firefox` job seems to be fine)

## What went wrong

After merging #24131, that specific runner now quits after an Internal rendering error is surfaced
https://github.com/bevyengine/bevy-example-runner/actions/runs/25469052098/job/74728737335 Look at the "Run Examples (linux)" portion

Note that this seems to have been happening before, but the new logic from the referenced PR will now make the job fail since the app will quit instead of being kept alive long enough for a screenshot. The run before has shader compilation errors but it succeeds since the app stays alive: https://github.com/bevyengine/bevy-example-runner/actions/runs/25461960104/job/74706142862

Snippet of the many validation/internal errors it spits out:
```
%cERROR%c crates/bevy_render/src/error_handler.rs:132%c Caught rendering error: Validation Error

Caused by:
  In Device::create_render_pipeline, label = 'opaque_mesh2d_pipeline'
    Internal error in ShaderStages(VERTEX) shader: 
 color: red; background: #444 color: gray; font-style: italic color: inherit
%cERROR%c %c 	Shader compilation failed:  log.target = "wgpu_hal::gles::device";
log.module_path = "wgpu_hal::gles::device";
log.file = "/home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-hal-29.0.3/src/gles/device.rs";
log.line = 211; color: red; background: #444 color: gray; font-style: italic color: inherit
%cERROR%c %c Shader translation error for stage ShaderStages(VERTEX):  log.target = "wgpu::backend::wgpu_core";
log.module_path = "wgpu::backend::wgpu_core";
log.file = "/home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-29.0.3/src/backend/wgpu_core.rs";
log.line = 1406; color: red; background: #444 color: gray; font-style: italic color: inherit
%cERROR%c %c Please report it to https://github.com/gfx-rs/wgpu log.target = "wgpu::backend::wgpu_core";
log.module_path = "wgpu::backend::wgpu_core";
log.file = "/home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-29.0.3/src/backend/wgpu_core.rs";
log.line = 1407; color: red; background: #444 color: gray; font-style: italic color: inherit
```

**Comment by mockersf** [comment]
works now, but likely fixed by a chromium update
