### PR TITLE
[Merged by Bors] - Update gilrs to v0.9

### LINKED ISSUE #4353: Firefox fails to load any wasm example with bevy builds on main (0.7.0 dev)
## Bevy version

28ba87e6c8f48a6b41b6743b748a72d41728523c

## Operating system & version

Windows 10 x64
Firefox 98.0.2 (64-bit)

## What you did

Built WASM of `text_debug` example with latest main branch as per WASM build instructions in examples readme.

## What you expected to happen

The example would load and show text.

## What actually happened

Shows just white screen and an error.

## Additional information
Firefox will load with WASM builds based on Bevy 0.6.1, but not with builds based on the current main. 
Screenshot is showing Chrome (Left) and firefox (right)
image
Points to here
image

Also interestingly enough firefox thinks the gpu is "HD graphics 400", where as chrome shows it as "5500" on a Thinkpad X1 Carbon 3rd gen.
The same thing happens with a W530 with a K1000M gpu, shows up as a gtx 480 if that makes any difference.
image

### LINKED ISSUE #4431: wasm panic in Firefox because of missing getGamePads API
## Bevy version

`main` `f907d67d7ed5cfd8b11b2ad78e9dfd6eeb913cea`

## Operating system & version

macOS 12.3

## What you did

Run the lighting example

## What you expected to happen

The example runs.

## What actually happened

The example panics.

## Additional information

```
panicked at 'error getting gamepads: JsValue(TypeError: getObject(...).getGamepads is not a function
init/imports.wbg.__wbg_getGamepads_125e8440ea7a98c8/<@http://0.0.0.0:8000/target/wasm_example.js:1071:35
handleError@http://0.0.0.0:8000/target/wasm_example.js:260:18
init/imports.wbg.__wbg_getGamepads_125e8440ea7a98c8@http://0.0.0.0:8000/target/wasm_example.js:1070:74
web_sys::features::gen_Navigator::Navigator::get_gamepads::h38f15820bcd54585@http://0.0.0.0:8000/target/wasm_example_bg.wasm:wasm-function[17624]:0x9e4430
gilrs_core::platform::platform::gamepad::Gilrs::next_event::ha502708d74993467@http://0.0.0.0:8000/target/wasm_example_bg.wasm:wasm-function[659]:0x24484f
gilrs_core::Gilrs::next_event::h1def7b279c39043e@http://0.0.0.0:8000/target/wasm_example_bg.wasm:wasm-function[25101]:0xa1cd38
gilrs::gamepad::Gilrs::next_event_priv::h581e4e4191b9fd6b@http://0.0.0.0:8000/target/wasm_example_bg.wasm:wasm-function[719]:0x272637
gilrs::gamepad::Gilrs::next_event::h795f889b0d271268@http:/…
wasm_example.js:420:21
```

### PR DESCRIPTION
**Pull request by james7132**
# Objective
Fixes #4353. Fixes #4431. Picks up fixes for a panic for `gilrs` when `getGamepads()` is not available. 

## Solution
Update the `gilrs` to `v0.9.0`. Changelog can be seen here: https://gitlab.com/gilrs-project/gilrs/-/commit/dba36f91869c823fb66f8633d2b650b430682f80

EDIT: Updated `uuid` to 1.1 to avoid duplicate dependencies. Added `nix`'s two dependencies as exceptions until `rodio` updates their deps.

### CODE REVIEW

**Comment by mockersf** [comment]
two duplicate dependencies:
* `nix`, coming from `alsa`. can probably be ignored until `alsa`/`cpal`/`rodio` update their dependencies
* `uuid`, coming from `bevy`: https://github.com/bevyengine/bevy/pull/4845. we should update those two close together

File: deny.toml [hunk 1]
```diff
@@ -49,6 +49,8 @@ skip = [
     { name = "ndk-sys", version = "0.2" },              # from winit v0.26.1
     { name = "stdweb", version = "0.1" },               # from rodio v0.15.0
     { name = "wasi",  version = "0.10"},                # from ahash v0.7.6
+    { name = "nix", version = "0.23.1" },               # from alsa v0.6.0
+    { name = "nix", version = "0.24.1" },               # from gilrs-core v0.4.0
```
Comment (mockersf) [inline deny.toml:53]:
```suggestion
```
no need to mention the two versions, that way we'll be notified if something start depending on a third version of `nix`

**Review by mockersf — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]
