### ISSUE TITLE
v0.11.2 unknown feature `proc_macro_span_shrink` when running: cargo apk run -p bevy_mobile_example

### ISSUE THREAD

**Issue by 00alia00** [bevyengine/bevy#9515]
## Bevy version
0.11.2

The release number or commit hash of the version you're using.
Tag: v0.11.2

## \[Optional\] Relevant system information
Windows / ndk: 25.1.8937393

## What you did
Tried to run the android example

alia@Arrakis MINGW64 /c/dev/bevy ((v0.11.2))
$ cargo apk run -p bevy_mobile_example
Using package `bevy_mobile_example` in `C:\dev\bevy\examples\mobile\Cargo.toml`
   Compiling proc-macro2 v1.0.54
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> C:\Users\alia\.cargo\registry\src\index.crates.io-6f17d22bba15001f\proc-macro2-1.0.54\src\lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

## What went wrong
Compile error

**Comment by mockersf** [comment]
what version of Rust are you using? Could you update it?

**Comment by 00alia00** [comment]
rustc 1.73.0-nightly (474709a9a 2023-08-03) ill update and see what happens :D

**Comment by 00alia00** [comment]
Same error after update to 1.73.0-nightly (6ef7d16be 2023-08-19)

**Comment by rlidwka** [comment]
https://github.com/rust-lang/rust/issues/113152

I suggest to remove `Cargo.lock`, run `cargo clean`, and try again. 

If the issue persists, try to determine why old version of `proc_macro2` is being installed.

**Comment by 00alia00** [comment]
@rlidwka Thanks that fixed it <3
