### ISSUE TITLE
Unlit materials cause shader panic

### ISSUE THREAD

**Issue by aevyrie** [bevyengine/bevy#2190]
## Bevy version

Commit e3435e5

**Confirmed the breaking change happened in 73f4a9d18f609e52d28e2963635560e0b78a2f9f**
## Operating system & version

Windows 10

## What you did

Existing plugins that use unlit materials now panic as soon as meshes with that material are shown. Results in the following panic:

```shell
thread 'main' panicked at 'Shader compilation error:
glslang_shader_parse:
Info log:
ERROR: 0:293: 'getDistanceAttenuation' : no matching overloaded function found
ERROR: 0:293: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.
```

Lines in question appear to be in the pbr frag shader here:

https://github.com/bevyengine/bevy/blob/73f4a9d18f609e52d28e2963635560e0b78a2f9f/crates/bevy_pbr/src/render_graph/pbr_pipeline/pbr.frag#L291-L292

**Comment by aevyrie** [comment]
I think I found the issue. Looks like a function that was previously only run if the material is not unlit, is now being run for unlit materials, and refers to the `getDistanceAttenuation` which is not defined for unlit materials.
