### ISSUE TITLE
Compilation errors in suballocation.rs with reduced features on 0.15.0-rc.3 (compiles with 0.15.0-rc.1)

### ISSUE THREAD

**Issue by goto64** [bevyengine/bevy#16259]
## Bevy version
0.15.0-rc.3

## Relevant system information
cargo 1.82.0
Windows 11 Home, 10.0.22631

## What you did
Trying to compile this branch: https://github.com/goto64/bevy_2d_screen_space_lightmaps/tree/prepare_0_15
Using the following as dependecies:
bevy = { version = "0.15.0-rc.3", default-features = false, features = [
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_winit",
    "bevy_asset",
    "bevy_sprite",
    "bevy_ui",
] }

## What went wrong
Compilation errors:
error[E0308]: mismatched types
   --> C:\Users\genet\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-hal-23.0.0\src\dx12\suballocation.rs:39:67
    |
39  |         device: gpu_allocator::d3d12::ID3D12DeviceVersion::Device(raw.clone()),
    |                 ------------------------------------------------- ^^^^^^^^^^^ expected `ID3D12Device`, found a different `ID3D12Device`
    |                 |
    |                 arguments to this enum variant are incorrect
    |
    = note: `ID3D12Device` and `ID3D12Device` have similar names, but are actually distinct types
note: `ID3D12Device` is defined in crate `windows`
   --> C:\Users\genet\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.58.0\src\Windows\Win32\Graphics\Direct3D12\mod.rs:655:1
    |
655 | windows_core::imp::define_interface!(ID3D12Device, ID3D12Device_Vtbl, 0x189819f1_1db6_4b57_be54_1821339b85f7);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: `ID3D12Device` is defined in crate `windows`
   --> C:\Users\genet\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.54.0\src\Windows\Win32\Graphics\Direct3D12\mod.rs:764:1
    |
764 | ::windows_core::imp::com_interface!(ID3D12Device, ID3D12Device_Vtbl, 0x189819f1_1db6_4b57_be54_1821339b85f7);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `windows` are being used?
note: tuple variant defined here
   --> C:\Users\genet\.cargo\registry\src\index.crates.io-6f17d22bba15001f\gpu-allocator-0.27.0\src\d3d12\mod.rs:243:5
    |
243 |     Device(ID3D12Device),
    |     ^^^^^^
    = note: this error originates in the macro `windows_core::imp::define_interface` which comes from the expansion of the macro `::windows_core::imp::com_interface` (in Nightly builds, run with -Z macro-backtrace for more info)

## Additional information
Compiles with 0.15.0-rc.1

**Comment by goto64** [comment]
After running `cargo update` it now compiles successfully, so that fixed something.

The output from `cargo tree --invert wgpu` was:

wgpu v23.0.0
|-- bevy_image v0.15.0-rc.3
|   |-- bevy_core_pipeline v0.15.0-rc.3
|   |   |-- bevy_internal v0.15.0-rc.3
|   |   |   `-- bevy v0.15.0-rc.3
|   |   |       `-- bevy_2d_screen_space_lightmaps v0.15.0 (C:\sandbox\bevy_2d_screen_space_lightmaps)
|   |   |       [dev-dependencies]
|   |   |       `-- bevy_2d_screen_space_lightmaps v0.15.0 (C:\sandbox\bevy_2d_screen_space_lightmaps)
|   |   |-- bevy_sprite v0.15.0-rc.3
|   |   |   |-- bevy_internal v0.15.0-rc.3 (*)
|   |   |   |-- bevy_text v0.15.0-rc.3
|   |   |   |   |-- bevy_internal v0.15.0-rc.3 (*)
|   |   |   |   `-- bevy_ui v0.15.0-rc.3
|   |   |   |       `-- bevy_internal v0.15.0-rc.3 (*)
|   |   |   `-- bevy_ui v0.15.0-rc.3 (*)
|   |   `-- bevy_ui v0.15.0-rc.3 (*)
|   |-- bevy_internal v0.15.0-rc.3 (*)
|   |-- bevy_mesh v0.15.0-rc.3
|   |   |-- bevy_picking v0.15.0-rc.3
|   |   |   |-- bevy_internal v0.15.0-rc.3 (*)
|   |   |   |-- bevy_sprite v0.15.0-rc.3 (*)
|   |   |   `-- bevy_ui v0.15.0-rc.3 (*)
|   |   `-- bevy_render v0.15.0-rc.3
|   |       |-- bevy_animation v0.15.0-rc.3
|   |       |   `-- bevy_ui v0.15.0-rc.3 (*)
|   |       |-- bevy_core_pipeline v0.15.0-rc.3 (*)
|   |       |-- bevy_internal v0.15.0-rc.3 (*)
|   |       |-- bevy_picking v0.15.0-rc.3 (*)
|   |       |-- bevy_sprite v0.15.0-rc.3 (*)
|   |       |-- bevy_text v0.15.0-rc.3 (*)
|   |       `-- bevy_ui v0.15.0-rc.3 (*)
|   `-- bevy_render v0.15.0-rc.3 (*)
|-- bevy_mesh v0.15.0-rc.3 (*)
`-- bevy_render v0.15.0-rc.3 (*)

**Comment by goto64** [comment]
Can be closed since it was solved by running `cargo update`
