### ISSUE TITLE
`bevy_gizmos` fails to compile with certain feature flag combinations

### ISSUE THREAD

**Issue by IQuick143** [bevyengine/bevy#21008]
## Bevy version and features

```toml
[package]
name = "gizmos_bug"
edition = "2021"

[dependencies]
bevy = { version="0.16.0", default-features=false, features = [
    "bevy_sprite",
    "bevy_render",
    "bevy_gizmos",
] }
```
Passes `cargo check`

```toml
[package]
name = "gizmos_bug"
edition = "2021"

[dependencies]
bevy = { version="0.17.0-rc", default-features=false, features = [
    "bevy_sprite",
    "bevy_render",
    "bevy_gizmos",
] }
```
Fails `cargo check` with:
```
error[E0432]: unresolved import `bevy_sprite_render`
  --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_gizmos-0.17.0-rc.1/src/pipeline_2d.rs:32:5
   |
32 | use bevy_sprite_render::{
   |     ^^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `bevy_sprite_render`
   |
   = help: if you wanted to use a crate named `bevy_sprite_render`, use `cargo add bevy_sprite_render` to add it to your `Cargo.toml`

error[E0433]: failed to resolve: use of unresolved module or unlinked crate `bevy_sprite_render`
  --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_gizmos-0.17.0-rc.1/src/pipeline_2d.rs:56:37
   |
56 |                     .ambiguous_with(bevy_sprite_render::queue_sprites)
   |                                     ^^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `bevy_sprite_render`
   |
   = help: if you wanted to use a crate named `bevy_sprite_render`, use `cargo add bevy_sprite_render` to add it to your `Cargo.toml`

error[E0433]: failed to resolve: use of unresolved module or unlinked crate `bevy_sprite_render`
  --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_gizmos-0.17.0-rc.1/src/pipeline_2d.rs:58:25
   |
58 |                         bevy_sprite_render::queue_material2d_meshes::<
   |                         ^^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `bevy_sprite_render`
   |
   = help: if you wanted to use a crate named `bevy_sprite_render`, use `cargo add bevy_sprite_render` to add it to your `Cargo.toml`

error[E0433]: failed to resolve: use of unresolved module or unlinked crate `bevy_sprite_render`
  --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_gizmos-0.17.0-rc.1/src/pipeline_2d.rs:59:29
   |
59 | ...                   bevy_sprite_render::ColorMaterial,
   |                       ^^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `bevy_sprite_render`
   |
   = help: if you wanted to use a crate named `bevy_sprite_render`, use `cargo add bevy_sprite_render` to add it to your `Cargo.toml`

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `bevy_gizmos` (lib) due to 4 previous errors
```

## Additional notes
Disabling either `bevy_sprite` or `bevy_render` removes the compile failure by not compiling the offending code in `bevy_gizmos`

**Comment by ChristopherBiscardi** [comment]
bevy_ecs_tilemap also saw this when migrating

**Comment by IQuick143** [comment]
The solution seems to be to enable the `bevy_sprite_render` feature as well, though looking at the offending code (which I believe is introduced by https://github.com/bevyengine/bevy/pull/20587/) it could easily just compile if it had the correct conditional compiles where necessary.

I don't know well how cargo flags work or what the desired solution is here. (Should `bevy_sprite_render` be enabled automatically when both `bevy_sprite` and `bevy_render` are?)
