### ISSUE TITLE
Spawning scenes with cameras no longer works

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy#11852]
## Bevy version

77c26f64ce0c1a538629a544b7020eb2d2b77466

## What you did

Exported a GLTF scene from Blender with a camera and loaded it in Bevy.

## What went wrong

The app crashed because CameraRenderGraph does not implement Reflect. This regressed in #10644.
For future reference, removing Reflect from a type that exists in a bundle used in scenes should almost never be allowed.

**Comment by alice-i-cecile** [comment]
I think we should fix this for 0.13.

**Comment by cart** [comment]
Reverting #10644 isn't enough because this also doesn't implement Reflect: https://github.com/bevyengine/bevy/pull/11412

**Comment by cart** [comment]
Yeah I think thats a good call. Probably not for 0.13 though.

**Comment by DasLixou** [comment]
Should we just enforce labels to derive reflect and then we reflect them via their path?

**Comment by cart** [comment]
Alrighty after reverting #10644 and adding a reflect_value impl to `wgpu::TextureUsages` in `bevy_reflect`, deriving Reflect on CameraMainTextureUsages, and registering the type, we're back in business:

```rust
use crate as bevy_reflect;

use bevy_reflect_derive::impl_reflect_value;

impl_reflect_value!(::wgpu::TextureUsages(Debug, Hash, PartialEq));
```

![image](https://github.com/bevyengine/bevy/assets/2694663/a4ebfdbd-e552-4197-94fc-666355f9cfb2)

It is broken for serialization scenarios (as TextureUsages is not serializable). But it fixes GLTF loading. I'm going to see if we can do the same reflect_value hack for #10644 to avoid needing to revert (but note that us moving away from strings for this will break serialization for that as well).

The TextureUsages serialization can be fixed by moving to the Image mirror types we'll be adding here: https://github.com/bevyengine/bevy/pull/11294#issuecomment-1928552369

> Should we just enforce labels to derive reflect and then we reflect them via their path?

The interned RenderGraph label serialization will be its own can of worms as we've moved to using types as identifiers. We'd likely need some type of TypePath -> label object registry for this. My new scene system would accommodate this type of exchange by supporting constructing the runtime types from different types in the scene, with access to a World context. (aka use the TypePath in the scene to grab the TypePath->Object mapping from a resource when spawning).

**Comment by cart** [comment]
Arg adding `wgpu` to `bevy_reflect` puts it _much_ earlier in the dependency tree. I'm getting a ~7 second clean compile time regression (on my fast computer that compiles main in ~30 seconds, so that will be magnified on the average computer).

**Comment by IceSentry** [comment]
> Arg adding wgpu to bevy_reflect puts it much earlier in the dependency tree. I'm getting a ~7 second clean compile time regression (on my fast computer that compiles main in ~30 seconds, so that will be magnified on the average computer).

Maybe we should define a custom bevy enum that is easy to reflect and match on it when we need the wgpu type?

**Comment by cart** [comment]
> Maybe we should define a custom bevy enum that is easy to reflect and match on it when we need the wgpu type?

Yeah thats where my head is at as well / what I was getting at with this comment:

> The TextureUsages serialization can be fixed by moving to the Image mirror types we'll be adding here: https://github.com/bevyengine/bevy/pull/11294#issuecomment-1928552369
