### PR TITLE
Improve error for when you try running a one-shot system with wrong `SystemId` type

### PR DESCRIPTION
**Pull request by hukasu**
# Objective

Improve error message when running a one-shot system with a `SystemId` of wrong type. 

## Solution

Added a resource to keep track of running one-shot systems, and return `Recursive` error if a system gets run before the end of their previous invocation. The error for not being able to `take` a `RegisteredSystem` is now `MaybeWrongType`.

## Testing

Minimal reproduction from #19005

## Showcase

```
// Old
2025-05-01T12:42:54.305283Z  WARN bevy_ecs::error::handler: Encountered an error in command `bevy_ecs::system::commands::command::run_system<()>::{{closure}}`: System SystemId(4v1#4294967300) tried to run itself recursively
2025-05-01T12:42:54.305311Z  WARN bevy_ecs::error::handler: Encountered an error in command `bevy_ecs::system::commands::command::run_system_with<bevy_ecs::system::input::In<&str>>::{{closure}}`: System SystemId(5v1#4294967301) tried to run itself recursively

// New
2025-05-05T14:21:44.918145Z  WARN bevy_ecs::error::handler: Encountered an error in command `bevy_ecs::system::commands::command::run_system<()>::{{closure}}`: Could not get system from `SystemId`, entity was `SystemId<(), Result<(), BevyError>>`
2025-05-05T14:21:44.918177Z  WARN bevy_ecs::error::handler: Encountered an error in command `bevy_ecs::system::commands::command::run_system_with<bevy_ecs::system::input::In<&str>>::{{closure}}`: Could not get system from `SystemId<In<&str>>`, entity was `SystemId<In<&str>, Result<(), BevyError>>`
```

## TODO
- [x] Add `TypeId` to `SystemIdMarker`
- [x] Migration guide for new enum variant

### CODE REVIEW

File: crates/bevy_ecs/src/system/system_registry.rs [hunk 1]
```diff
@@ -332,25 +337,36 @@ impl World {
         I: SystemInput + 'static,
         O: 'static,
     {
+        if !self.is_resource_added::<RunSystemStack>() {
+            self.init_resource::<RunSystemStack>();
+        }
```
Comment (chescock) [inline crates/bevy_ecs/src/system/system_registry.rs:342]: `init_resource` checks whether the resource already exists, so you can simplify this.

```suggestion
        self.init_resource::<RunSystemStack>();
```

File: crates/bevy_ecs/src/system/system_registry.rs [hunk 2]
```diff
@@ -362,6 +378,8 @@ impl World {
                 ret
             });
 
+        self.resource_mut::<RunSystemStack>().remove(&id.entity);
```
Comment (chescock) [inline crates/bevy_ecs/src/system/system_registry.rs:381]: This could technically panic if a malicious system finds the `RunSystemStack` resource by ID and removes it.  It might be a little safer like

```suggestion
        if let Some(run_system_stack) = self.get_resource_mut::<RunSystemStack>() {
            run_system_stack.remove(&id.entity);
        }
```

We may even want to do the same thing for `insert`, since a user could register a malicious observer that runs during `take::<RegisteredSystem>`.

**Review by chescock — APPROVED** [review]
Looks good!  

One possible follow-up might be to try to store the type name or type id in `SystemIdMarker`.  Then we could generate a message with both the expected and actual type, which might have helped in the linked issue where there was confusion between `()` and `Result`.  (Hmm, and maybe then we wouldn't even need `RunSystemStack`, since we could detect type mismatch and assume anything else is a recursive call?)

File: crates/bevy_ecs/src/system/system_registry.rs (hunk 2 above)
Comment (hukasu) [reply crates/bevy_ecs/src/system/system_registry.rs:381]: maybe it is impossible for that to happen in between the `init_resource` and `insert`, but i will have on `remove`

Comment (hukasu) [reply crates/bevy_ecs/src/system/system_registry.rs:381]: would the observer of `take` happen immediately or after the end of method? i don't know how that works when fiddling with `World`

File: crates/bevy_ecs/src/system/system_registry.rs [hunk 3]
```diff
@@ -501,6 +523,10 @@ pub enum RegisteredSystemError<I: SystemInput = (), O = ()> {
         /// The returned parameter validation error.
```
Comment (MrGVSV) [inline crates/bevy_ecs/src/system/system_registry.rs:523]: Does this doc link render correctly (i.e. without the `field` specifier)?

Comment (hukasu) [reply crates/bevy_ecs/src/system/system_registry.rs:523]: ops, copy-paste comment, will fix

File: crates/bevy_ecs/src/system/system_registry.rs [hunk 4]
```diff
@@ -332,25 +337,37 @@ impl World {
...
+        // Initialize the system
         if !initialized {
             system.initialize(self);
             initialized = true;
         }
 
+        let Some(mut sys_stack) = self.get_resource_mut::<RunSystemStack>() else {
+            panic!("`RunSystemStack` should never be removed during the execution of a one-shot system.");
+        };
+        sys_stack.insert(id.entity);
```
Comment (chescock) [inline crates/bevy_ecs/src/system/system_registry.rs:369]: I think you can simplify the "or panic" logic with `expect` (here and below).  

```suggestion
        self.get_resource_mut::<RunSystemStack>()
            .expect("`RunSystemStack` should never be removed during the execution of a one-shot system.")
            .insert(id.entity);
```

File: crates/bevy_ecs/src/system/system_registry.rs [hunk 5]
```diff
@@ -332,25 +337,37 @@ impl World {
...
-        let RegisteredSystem {
+        let Some(RegisteredSystem {
             mut initialized,
             mut system,
-        } = entity
-            .take::<RegisteredSystem<I, O>>()
-            .ok_or(RegisteredSystemError::Recursive(id))?;
+        }) = entity.take::<RegisteredSystem<I, O>>()
+        else {
+            return Err(RegisteredSystemError::MaybeIncorrectType(id));
```
Comment (chescock) [inline crates/bevy_ecs/src/system/system_registry.rs:357]: I think this could keep doing `ok_or` and `?` like the old code, instead of an explicit `return`.  You're just changing `Recursive` to `MaybeIncorrectType`, right?

File: crates/bevy_ecs/src/system/system_registry.rs [hunk 6]
```diff
@@ -915,4 +967,25 @@ mod tests {
...
+        });
+    }
+
+    #[test]
+    #[should_panic]
+    fn removing_system_stack_with_observer() {
+        let mut world = World::new();
+        world.add_observer(
+            |_trigger: Trigger<OnRemove, RegisteredSystem<(), ()>>, world: &mut World| {
+                world.remove_resource::<RunSystemStack>();
```
Comment (chescock) [inline crates/bevy_ecs/src/system/system_registry.rs:986]: I think this is the cause of the miri failure.  It's not supposed to be valid to use an exclusive system as an observer!  I'm pretty sure it's a bug in the observer code that it allows this to be added.  Maybe we need to open an issue for that?

It should work to use `Commands` instead of `&mut World`, though.  

```suggestion
            |_trigger: Trigger<OnRemove, RegisteredSystem<(), ()>>, mut commands: Commands| {
                commands.remove_resource::<RunSystemStack>();
```

**Review by chescock — APPROVED** [review]
Looks good!  The miri failure needs to be fixed, but I *think* using `Commands` will be enough.  I also left a few style suggestions, but nothing blocking.

File: crates/bevy_ecs/src/system/system_registry.rs (hunk 5 above)
Comment (hukasu) [reply crates/bevy_ecs/src/system/system_registry.rs:357]: on the first commit the logic to check if it is recursing was done inside the else, but after changing it to be done before i never returned to the `ok_or`, will do

**Comment by hymm** [comment]
`run_system` can be potentially very hot if the user is running it in a loop. This is adding the overhead of initializing the resource and potentially allocating to grow the stack to each run of a system. This should probably be at least gated to debug buidls. But I think my preference is to not add a stack and just add to the existing error message that the wrong type of system id may have been passed.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Adding an enum variant is breaking, and needs a tiny migration guide.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
> `run_system` can be potentially very hot if the user is running it in a loop. This is adding the overhead of initializing the resource and potentially allocating to grow the stack to each run of a system. This should probably be at least gated to debug buidls. But I think my preference is to not add a stack and just add to the existing error message that the wrong type of system id may have been passed.

I agree with this: I'm nervous about slowing this down to improve diagnostics, especially in release. I would prefer to slim this down if at all possible, or add benchmarks showing that this isn't detectable if not.

**Comment by hukasu** [comment]
I already removed the stack following chescock's suggestion

**Comment by hukasu** [comment]
merged with main, but now the reproduction i had can't compile (bisected to 6e918f56d840f03fa0f2862b8723f046b5eafbac) due to 
```
error[E0283]: type annotations needed
   --> src/bin/issue19005.rs:38:23
    |
38  |                 world.register_system(print_message).entity(),
    |                       ^^^^^^^^^^^^^^^ cannot infer type for type parameter `Out`
    |
    = note: multiple `impl`s satisfying `std::result::Result<(), BevyError>: IntoResult<_>` found in the `bevy_ecs` crate:
            - impl<T> IntoResult<T> for T;
            - impl<T> IntoResult<T> for std::result::Result<T, BevyError>;
    = note: required for `for<'a> fn(bevy::prelude::In<&'a str>) -> std::result::Result<(), BevyError> {print_message}` to implement `IntoSystem<bevy::prelude::In<&str>, _, (IsFunctionSystem, (HasSystemInput, fn(bevy::prelude::In<&str>) -> std::result::Result<(), BevyError>))>`
```

File: crates/bevy_ecs/src/system/system_registry.rs [hunk 7]
```diff
@@ -36,11 +38,40 @@ impl<I, O> RegisteredSystem<I, O> {
     }
 }
 
+#[derive(Debug, Clone, Copy)]
+#[cfg_attr(feature = "bevy_reflect", derive(Reflect))]
+#[cfg_attr(feature = "bevy_reflect", reflect(Debug, Default, Clone))]
+struct TypeIdAndName(TypeId, &'static str);
```
Comment (alice-i-cecile) [inline crates/bevy_ecs/src/system/system_registry.rs]: Named struct please.

Comment (alice-i-cecile) [inline crates/bevy_ecs/src/system/system_registry.rs]: The `name` here needs to be controlled via the new `debug` feature flag to avoid allocating and leaking strings in production.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
A few things to clean up, but I'm fundamentally on board.

File: crates/bevy_ecs/src/system/system_registry.rs (hunk 7 above)
Comment (hukasu) [reply crates/bevy_ecs/src/system/system_registry.rs]: the only source of `name` is `core::any::type_name`, can this cause the leaks?

Comment (alice-i-cecile) [reply crates/bevy_ecs/src/system/system_registry.rs]: Yes, this exposes implementation details by recording names in memory. The memory usage is the much larger problem though.

Comment (hukasu) [reply crates/bevy_ecs/src/system/system_registry.rs]: `bevy_ecs` does not have a `debug` feature, should one be introduced? should it be called `debug`? the crate that received the `debug` feature was just `bevy_utils`

Comment (alice-i-cecile) [reply crates/bevy_ecs/src/system/system_registry.rs]: Ah, I see. Yes, we should synchronize that, and control it with the same `bevy`-level flag.

Comment (hukasu) [reply crates/bevy_ecs/src/system/system_registry.rs]: then just waiting for local ci to finish

Comment (chescock) [reply crates/bevy_ecs/src/system/system_registry.rs]: You shouldn't need a new feature flag.  I think you can just use the `DebugName` type here instead of `&str`.  It has a `type_name<T>` constructor.

**Comment by hukasu** [comment]
these commits are without chescocks suggestion, will see to it now

File: crates/bevy_ecs/src/system/system_registry.rs (hunk 7 above)
Comment (hukasu) [reply crates/bevy_ecs/src/system/system_registry.rs]: i had `Reflect` derived for my `TypeIdAndName`, but `DebugName` does not impls `Reflect`, maybe i can remove the derive, i just added for adding

Comment (chescock) [reply crates/bevy_ecs/src/system/system_registry.rs]: Oh, I didn't think about `Reflect`!  I bet the long-term answer is that we should `impl Reflect for DebugName` like we do for `&'static str` and `Cow<'static, str>`, but that should probably be a separate PR, so I'd vote for removing that derive for now.

Comment (hukasu) [reply crates/bevy_ecs/src/system/system_registry.rs]: that would require also removing the derive from `SystemIdMarker` which has `Reflect` since before this PR, and i made distinct errors for the error variant for when there is `debug` and when there isn't, which i like more than just having `Could not get system from ``Enable the debug feature to see the name``, entity was ``SystemId<Enable the debug feature to see the name, Enable the debug feature to see the name>`` ` as what the user sees

Comment (chescock) [reply crates/bevy_ecs/src/system/system_registry.rs]: I think the long-term goal should be to have a single feature flag and use the `DebugName` type consistently.  This is exactly the sort of thing it should be useful for, so if it's giving us bad error messages then we should try to fix that!  

But it sounds like we'll need `impl Reflect for DebugName` before we can actually use it here, and I'm happy to approve any incremental progress for now!

Comment (hukasu) [reply crates/bevy_ecs/src/system/system_registry.rs]: I did you suggestion

File: crates/bevy_ecs/src/system/function_system.rs [hunk 8]
```diff
@@ -608,7 +608,7 @@ impl<T> IntoResult<T> for Result<T, RunSystemError> {
 
 impl<T> IntoResult<T> for Result<T, BevyError> {
     fn into_result(self) -> Result<T, RunSystemError> {
-        Ok(self?)
+        self.map_err(RunSystemError::from)
```
Comment (chescock) [inline crates/bevy_ecs/src/system/function_system.rs]: Is this change necessary?

File: crates/bevy_ecs/src/system/system_registry.rs [hunk 9]
```diff
@@ -343,6 +374,19 @@ impl World {
             .get_entity_mut(id.entity)
             .map_err(|_| RegisteredSystemError::SystemIdNotRegistered(id))?;
 
+        let Some(system_id_marker) = entity.get::<SystemIdMarker>() else {
+            return Err(RegisteredSystemError::SystemNotCached);
```
Comment (chescock) [inline crates/bevy_ecs/src/system/system_registry.rs]: The docs for `SystemNotCached` say "A cached system was removed by value, but no system with its type was found".  I think we either want to return `SystemIdNotRegistered` here, or update the docs.

File: tools/ci/src/commands/test.rs [hunk 10]
```diff
@@ -13,14 +13,26 @@ impl Prepare for TestCommand {
         let jobs = args.build_jobs();
         let test_threads = args.test_threads();
 
-        vec![PreparedCommand::new::<Self>(
-            cmd!(
-                sh,
-                // `--benches` runs each benchmark once in order to verify that they behave
-                // correctly and do not panic.
-                "cargo test --workspace --lib --bins --tests --benches {no_fail_fast...} {jobs...} -- {test_threads...}"
+        let jobs_ref = &jobs;
```
Comment (chescock) [inline tools/ci/src/commands/test.rs]: These changes seem unrelated.

File: crates/bevy_ecs/src/system/system_registry.rs [hunk 11]
```diff
@@ -941,15 +960,22 @@ mod tests {
...
         fn world_recursive(world: &mut World) {
-            match world.run_system_cached(world_recursive) {
-                Ok(_) => panic!("Calling an already running system should fail."),
-                Err(RegisteredSystemError::Recursive(_)) => (),
-                Err(err) => panic!(
-                    "Should've failed with `Recursive`, but failed with `{}`.",
-                    err
-                ),
-            };
+            let sys_id = world.register_system_cached(world_recursive);
```
Comment (chescock) [inline crates/bevy_ecs/src/system/system_registry.rs]: Why did you change this test?  The first version you had verified that `run_system_cached` returned `RegisteredSystemError::Recursive` when called recursively.  Don't we still need to test that?  ... oh, I see, `run_system_cached` never returns `RegisteredSystemError::Recursive` because it always re-registers the system.  You'd need to use `register_system` and `run_system` to check that case.  

I'd be inclined to remove the current version of the test, since I don't think it's testing anything especially interesting.  It would be even better if we could make a test that verified `RegisteredSystemError::Recursive` is returned when appropriate, but we didn't have that before so I don't think it's critical.

File: crates/bevy_ecs/src/system/system_registry.rs [hunk 12]
```diff
@@ -343,6 +374,19 @@ impl World {
             .get_entity_mut(id.entity)
             .map_err(|_| RegisteredSystemError::SystemIdNotRegistered(id))?;
 
+        let Some(system_id_marker) = entity.get::<SystemIdMarker>() else {
```
Comment (chescock) [inline crates/bevy_ecs/src/system/system_registry.rs]: If we're really worried about performance, it might make sense to only do the `SystemIdMarker` checks if `take::<RegisteredSystem<I, O>>()` returns `Err`.  Then we wouldn't have to pay for them in the common case where the system is registered correctly.

**Review by chescock — APPROVED** [review]
Looks good!  I left a few thoughts, but nothing that should be blocking.

File: crates/bevy_ecs/src/system/function_system.rs (hunk 8 above)
Comment (alice-i-cecile) [reply crates/bevy_ecs/src/system/function_system.rs]: I would prefer to revert this change.

File: tools/ci/src/commands/test.rs (hunk 10 above)
Comment (alice-i-cecile) [reply tools/ci/src/commands/test.rs]: These changes should be reverted.

File: crates/bevy_ecs/src/system/system_registry.rs (hunk 11 above)
Comment (alice-i-cecile) [reply crates/bevy_ecs/src/system/system_registry.rs]: I don't see how this test was changed? I agree that this test can be cut though.

File: crates/bevy_ecs/src/system/system_registry.rs (hunk 12 above)
Comment (alice-i-cecile) [reply crates/bevy_ecs/src/system/system_registry.rs]: Good idea!

File: crates/bevy_ecs/src/system/system_registry.rs (hunk 9 above)
Comment (alice-i-cecile) [reply crates/bevy_ecs/src/system/system_registry.rs]: I agree; the error type needs to be changed.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
Elevating @chescock's feedback to blocking :) I agree with it, and want it cleaned up before we merge this.

File: crates/bevy_ecs/src/system/system_registry.rs (hunk 11 above)
Comment (hukasu) [reply crates/bevy_ecs/src/system/system_registry.rs]: it changed from a previous commit on the PR

**Comment by hukasu** [comment]
@alice-i-cecile you approved before i pushed the final commits

**Comment by alice-i-cecile** [comment]
Ah, thanks for the heads up. I'll re-review in a bit.

**Review by chescock — APPROVED** [review]
