### PR TITLE
Ensure `bevy_utils` is included with `std` feature

### LINKED ISSUE #18200: Project that depends on Bevy with no default features but just feature [std] fails to compile (use of unresolved module or unlinked crate `bevy_utils`)
## Bevy version

0.16.0-dev
 commit: ab38b610011cdb66afbfcc95a79f2d6db44edce8

## What you did

I've created a brand new project with `cargo new bevy-example`
and added a bevy dependency to my Cargo.toml like so:

```toml
[package]
name = "bevy-example"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "ab38b610011cdb66afbfcc95a79f2d6db44edce8", default-features = false, features = ["std"] }
```

## What went wrong

doing `cargo build` results in this compilation error:

Image

## Additional information

I'm not sure if I can use bevy with feature `std` on it's own, but this issue persists even if I use features `std` and `async_executor`.

You can get this exact compilation error if you clone bevy and try to build it with this command:
`cargo build --no-default-features --features std`

I think this may be caused by #17955 :( (I've followed the migration guide for that change but that hasn't resolved my error)

### PR DESCRIPTION
**Pull request by bushrat011899**
# Objective

- Fixes #18200

## Solution

- Ensure `bevy_utils` is included with `bevy_transform/std`

## Testing

- `cargo build  --no-default-features --features std`

## Notes

Compilation failure was caused by `bevy_transform`'s new parallel propagation system requiring `bevy_utils/std` when `bevy_transform/std` was active, but it was left optional. Additionally, `bevy_transform/async_executor` wasn't being enabled by `bevy/async_executor`.

### CODE REVIEW

**Comment by bushrat011899** [comment]
check-advisories failure is unrelated to this PR.

**Review by mnmaita — APPROVED** [review]

**Review by aevyrie — APPROVED** [review]
