### ISSUE TITLE
Standalone bevy_ecs tests fail to compile

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#20542]
## Bevy version

ed13d9b0e2572c9ce6260dd8f5fd420baf4023a3

## What you did

Attempted to run a single test in `bevy_ecs`.

The exact command run was:

```
cargo test --package bevy_ecs --lib --all-features -- world::error::tests::fixing_panicking_entity_commands --exact --show-output
```

That particular test doesn't exist on `main`: I was attempting to fix a different issue.

## What went wrong

```
error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<impl Future<Output = _>>` in the current scope
   --> crates/bevy_tasks/src/task_pool.rs:484:22
    |
483 |                   let _result = AssertUnwindSafe(executor.run(tick_forever))
    |  _______________________________-
484 | |                     .catch_unwind()
    | |                     -^^^^^^^^^^^^ method not found in `AssertUnwindSafe<impl Future<Output = _>>`
    | |_____________________|
    |

error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<{async block@crates/bevy_tasks/src/task_pool.rs:500:36: 500:41}>` in the current scope
   --> crates/bevy_tasks/src/task_pool.rs:505:62
    |
505 |                 let _result = AssertUnwindSafe(tick_forever).catch_unwind().await.is_ok();
    |                                                              ^^^^^^^^^^^^ method not found in `AssertUnwindSafe<{async block@crates/bevy_tasks/src/task_pool.rs:500:36: 500:41}>`

error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<impl Future<Output = _>>` in the current scope
   --> crates/bevy_tasks/src/task_pool.rs:525:22
    |
524 |                   let _result = AssertUnwindSafe(executor.run(tick_forever))
    |  _______________________________-
525 | |                     .catch_unwind()
    | |                     -^^^^^^^^^^^^ method not found in `AssertUnwindSafe<impl Future<Output = _>>`
    | |_____________________|
    |

error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<{async block@crates/bevy_tasks/src/task_pool.rs:540:36: 540:41}>` in the current scope
   --> crates/bevy_tasks/src/task_pool.rs:545:62
    |
545 |                 let _result = AssertUnwindSafe(tick_forever).catch_unwind().await.is_ok();
    |                                                              ^^^^^^^^^^^^ method not found in `AssertUnwindSafe<{async block@crates/bevy_tasks/src/task_pool.rs:540:36: 540:41}>`

error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<Fut>` in the current scope
   --> crates/bevy_tasks/src/task_pool.rs:649:40
    |
649 |             .spawn(AssertUnwindSafe(f).catch_unwind())
    |                                        ^^^^^^^^^^^^ method not found in `AssertUnwindSafe<Fut>`

error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<Fut>` in the current scope
   --> crates/bevy_tasks/src/task_pool.rs:665:40
    |
665 |             .spawn(AssertUnwindSafe(f).catch_unwind())
    |                                        ^^^^^^^^^^^^ method not found in `AssertUnwindSafe<Fut>`

error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<Fut>` in the current scope
   --> crates/bevy_tasks/src/task_pool.rs:682:40
    |
682 |             .spawn(AssertUnwindSafe(f).catch_unwind())
    |                                        ^^^^^^^^^^^^ method not found in `AssertUnwindSafe<Fut>`

error[E0432]: unresolved import `__automatic_type_registration_impl`
   --> crates/bevy_reflect/src/lib.rs:820:17
    |
820 |         pub use __automatic_type_registration_impl::*;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `__automatic_type_registration_impl`
    |
    = help: if you wanted to use a crate named `__automatic_type_registration_impl`, use `cargo add __automatic_type_registration_impl` to add it to your `Cargo.toml`
```

## Additional information

Likely introduced by #15030.

**Comment by alice-i-cecile** [comment]
This compile failure only occurs with --all-features enabled.

**Comment by eugineerd** [comment]
`__automatic_type_registration_impl` error is due to `reflect_auto_register` enabling just `bevy_reflect/auto_register`, which requires either `bevy_reflect/auto_register_inventory` or `bevy_reflect/auto_register_static` to function. I think the reason this is separated into 3 features is because if we make `auto_register` == `auto_register_inventory`, then in the `auto_register_static` case we'd still have to download `inventory` since it'd require `auto_register` feature. I think it might be fine since `inventory` should still compile even on unsupported systems, it would just not do anything.

I don't know what all the `catch_unwind` errors are about though.

**Comment by alice-i-cecile** [comment]
Working notes:

<details>

The `catch_unwind` errors appear to be in `bevy_tasks`, and ultimately come from `core`. Looking at the source code, I noticed a `since = "1.9.0"` annotation. I bet I need to update Rust locally!

And doing so updates me to... Rust 1.89. What the heck. Okay, opening the docs, the problem becomes clearer: [`catch_unwind`](https://docs.rs/futures-lite/2.6.1/futures_lite/future/trait.FutureExt.html#method.catch_unwind) is an `std` method only!

Okay, so the whole of [`task_pool.rs`](https://github.com/bevyengine/bevy/blob/d422e478b33b24ae3374f696008386e927980627/crates/bevy_tasks/src/task_pool.rs) requires `std`, which is not being enable during tests. That's good and bad: we want `bevy_ecs` to be able to run without `std`. Bad because somehow this code was getting compiled in?

Uh, that's not great. [Our feature flagging](https://github.com/bevyengine/bevy/blob/d422e478b33b24ae3374f696008386e927980627/crates/bevy_tasks/src/lib.rs#L105) should have stopped that.

Wait no, we're running these tests with `all-features`? What? That's extra weird.

</details>

Conclusion: paging @bushrat011899 @NthTensor for help. Something is broken with the `std` `cfg` flags in `bevy_tasks`, likely originating in https://github.com/bevyengine/bevy/pull/20369.

To reproduce, run:

```
cargo test --package bevy_ecs --lib --all-features -- change_detection::tests::change_expiration --exact --show-output 
```

Critically, this only occurs with all-features enabled.

**Comment by NthTensor** [comment]
Sounds like a mistake, I'll look into this tomorrow.
