### ISSUE TITLE
Project that depends on Bevy with no default features but just feature [std] fails to compile (use of unresolved module or unlinked crate `bevy_utils`)

### ISSUE THREAD

**Issue by alexgershberg** [bevyengine/bevy#18200]
## Bevy version

0.16.0-dev
 commit: ab38b610011cdb66afbfcc95a79f2d6db44edce8

## What you did

I've created a brand new project with `cargo new bevy-example`
and added a bevy dependency to my Cargo.toml like so:

```toml
[package]
name = "bevy-example"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "ab38b610011cdb66afbfcc95a79f2d6db44edce8", default-features = false, features = ["std"] }
```

## What went wrong

doing `cargo build` results in this compilation error:

<img width="953" alt="Image" src="https://github.com/user-attachments/assets/7cc33dc5-0b1c-4c53-9901-dd69ee071640" />

## Additional information

I'm not sure if I can use bevy with feature `std` on it's own, but this issue persists even if I use features `std` and `async_executor`.

You can get this exact compilation error if you clone bevy and try to build it with this command:
`cargo build --no-default-features --features std`

I think this may be caused by #17955 :( (I've followed the migration guide for that change but that hasn't resolved my error)

**Comment by alexgershberg** [comment]
@bushrat011899 We had a chat about this on Bevy discord, thought I would follow up with a GitHub issue
