### ISSUE TITLE
Cannot derive `Reflect` on a struct with `Option<Box<T>>` field where `T: Reflect`

### ISSUE THREAD

**Issue by umut-sahin** [bevyengine/bevy#10393]
## Bevy version

v0.12

## What you did

```rust
#[derive(Reflect)]
pub struct Foo<T: Reflect> {
    pub problem: Option<Box<T>>,
}
```

## What went wrong

```
error[E0277]: the trait bound `std::boxed::Box<T>: TypePath` is not satisfied
  --> src/bug.rs:5:18
   |
25 |     pub problem: Option<Box<T>>,
   |                  ^^^^^^^^^^^^^^ the trait `TypePath` is not implemented for `std::boxed::Box<T>`
   |
```

## Additional information

This was working on v0.11.

**Comment by MrGVSV** [comment]
Related to #9929 and #6098
