### PR TITLE
[Merged by Bors] - Fix the new nightly CI errors

### PR DESCRIPTION
**Pull request by DJMcNab**
# Objective

- CI is failing again
- These failures result from https://github.com/rust-lang/rust/pull/85200

## Solution

- Fix the errors which result from this by using the given fields
- I also removed the now unused `Debug` impl.

I suspect that we shouldn't use -D warnings for nightly CI - ideally we'd get a discord webhook message into some (non-#github) dedicated channel on warnings. 

But this does not implement that.

### CODE REVIEW

**Review by Weibye — APPROVED** [review]

**Review by IceSentry — APPROVED** [review]
This fixes the issue, but I feel like this is a false positive on clippy side. The field was used here.

**Review by MinerSebas — APPROVED** [review]

**Comment by cart** [comment]
Relevant: https://github.com/rust-lang/rust/issues/88900
