### ISSUE TITLE
Reflection of references is broken in bevy_reflect 0.17

### ISSUE THREAD

**Issue by oliver-dew** [bevyengine/bevy#21282]
Minimal reproducible example: https://github.com/oliver-dew/ReflectMRE

## Bevy version and features

- bevy_reflect 0.17-rc.2

## What you did

Previously, you could reflect a reference (see bevy0.16 tag in above repo):

```
/// Builds in bevy_reflect 0.16
#[derive(Reflect)]
struct A<'a> {
    b: &'a i32
}
```

## What went wrong

In 0.17, the above does not build (see bevy0.17 tag in above repo). You get these errors:

```
error[E0277]: `&'a i32` does not implement `GetTypeRegistration` so cannot be registered for reflection
 --> src/lib.rs:6:8
  |
6 |     b: &'a i32
  |        ^^^^^^^ the trait `GetTypeRegistration` is not implemented for `&'a i32`
  |
  = note: consider annotating `&'a i32` with `#[derive(Reflect)]`
  = note: required for `&'a i32` to implement `RegisterForReflection`
help: consider removing the leading `&`-reference
  |
6 -     b: &'a i32
6 +     b: i32
  |

error[E0277]: `&'a i32` does not implement `Typed` so cannot provide static type information
  --> src/lib.rs:6:8
   |
6  |     b: &'a i32
   |        ^^^^^^^ the trait `Typed` is not implemented for `&'a i32`
   |
   = note: consider annotating `&'a i32` with `#[derive(Reflect)]`
   = note: required for `&'a i32` to implement `MaybeTyped`
note: required by a bound in `NamedField::new`
  --> /Users/oliverdew/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_reflect-0.17.0-rc.2/src/fields.rs:23:36
   |
23 |     pub fn new<T: PartialReflect + MaybeTyped + TypePath>(name: &'static str) -> Self {
   |                                    ^^^^^^^^^^ required by this bound in `NamedField::new`
help: consider removing the leading `&`-reference
   |
6  -     b: &'a i32
6  +     b: i32
   |

error[E0277]: `&'a i32` does not implement `PartialReflect` so cannot be introspected
 --> src/lib.rs:4:10
  |
4 | #[derive(Reflect)]
  |          ^^^^^^^ the trait `PartialReflect` is not implemented for `&'a i32`
  |
  = note: consider annotating `&'a i32` with `#[derive(Reflect)]`
  = help: the trait `PartialReflect` is implemented for `i32`
  = note: required for the cast from `&&'a i32` to `&dyn PartialReflect`
  = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `&'a i32` does not implement `PartialReflect` so cannot be introspected
 --> src/lib.rs:4:10
  |
4 | #[derive(Reflect)]
  |          ^^^^^^^ the trait `PartialReflect` is not implemented for `&'a i32`
  |
  = note: consider annotating `&'a i32` with `#[derive(Reflect)]`
  = help: the trait `PartialReflect` is implemented for `i32`
  = note: required for the cast from `&mut &'a i32` to `&mut (dyn PartialReflect + 'static)`
  = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `&i32` does not implement `PartialReflect` so cannot be introspected
 --> src/lib.rs:4:10
  |
4 | #[derive(Reflect)]
  |          ^^^^^^^ the trait `PartialReflect` is not implemented for `&i32`
  |
  = note: consider annotating `&i32` with `#[derive(Reflect)]`
  = help: the trait `PartialReflect` is implemented for `i32`
  = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `&'a i32` does not implement `PartialReflect` so cannot be introspected
 --> src/lib.rs:6:8
  |
6 |     b: &'a i32
  |        ^^^^^^^ the trait `PartialReflect` is not implemented for `&'a i32`
  |
  = note: consider annotating `&'a i32` with `#[derive(Reflect)]`
help: consider removing the leading `&`-reference
  |
6 -     b: &'a i32
6 +     b: i32
  |

error[E0277]: `&'a i32` does not implement `FromReflect` so cannot be created through reflection
 --> src/lib.rs:6:8
  |
6 |     b: &'a i32
  |        ^^^^^^^ the trait `FromReflect` is not implemented for `&'a i32`
  |
  = note: consider annotating `&'a i32` with `#[derive(Reflect)]`
help: consider removing the leading `&`-reference
  |
6 -     b: &'a i32
6 +     b: i32
```

**Comment by alice-i-cecile** [comment]
@eugineerd suspects that this is caused by https://github.com/bevyengine/bevy/pull/19929. We should just revert that.

**Comment by alice-i-cecile** [comment]
>  I suspect the right course of action in that case is to just not derive Reflect for those structs in the first place since they aren't usable for reflection anyway 

- @eugineerd [on Discord](https://discord.com/channels/691052431525675048/1404237363550486751/1422326982003265667).

We should document that this isn't supported (and probably change the trait bounds to require 'static), and users should migrate by removing these reflection derives.

**Comment by S4ndf1re** [comment]
Is the same true for structs containing function types?


```rust
#[derive(Component, Reflect, Clone, PartialEq, Debug)]
pub struct TextAnimator {
    string: String,
    function: fn(t: f32, text: &str) -> String,
    counter: f32,
    mode: DurationMode,

```

This is taken from the bevy_lunex crate, which apparently compiled fine in 0.16. After upgrading to bevy 0.17, this seems to not compile anymore with similar looking errors:

```text
error[E0277]: `for<'a> fn(f32, &'a str) -> std::string::String` does not implement `GetTypeRegistration` so cannot be registered for reflection
  --> crate/src/textanim.rs:15:15
   |
15 |     function: fn(t: f32, text: &str) -> String,
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `bevy_reflect::GetTypeRegistration` is not implemented for `for<'a> fn(f32, &'a str) -> std::string::String`
   |
   = note: consider annotating `for<'a> fn(f32, &'a str) -> std::string::String` with `#[derive(Reflect)]`
   = note: required for `for<'a> fn(f32, &'a str) -> std::string::String` to implement `RegisterForReflection`

error[E0277]: `for<'a> fn(f32, &'a str) -> std::string::String` does not implement `Typed` so cannot provide static type information
  --> crate/src/textanim.rs:15:15
   |
15 |     function: fn(t: f32, text: &str) -> String,
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `bevy_reflect::Typed` is not implemented for `for<'a> fn(f32, &'a str) -> std::string::String`
   |
   = note: consider annotating `for<'a> fn(f32, &'a str) -> std::string::String` with `#[derive(Reflect)]`
   = note: required for `for<'a> fn(f32, &'a str) -> std::string::String` to implement `bevy_reflect::MaybeTyped`
note: required by a bound in `NamedField::new`
  --> /Users/jankleinmann/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_reflect-0.17.2/src/fields.rs:23:36
   |
23 |     pub fn new<T: PartialReflect + MaybeTyped + TypePath>(name: &'static str) -> Self {
   |                                    ^^^^^^^^^^ required by this bound in `NamedField::new`

error[E0277]: `for<'a> fn(f32, &'a str) -> std::string::String` does not implement `PartialReflect` so cannot be introspected
  --> crate/src/textanim.rs:12:21
   |
12 | #[derive(Component, Reflect, Clone, PartialEq, Debug)]
   |                     ^^^^^^^ the trait `bevy_reflect::PartialReflect` is not implemented for `for<'a> fn(f32, &'a str) -> std::string::String`
   |
   = note: consider annotating `for<'a> fn(f32, &'a str) -> std::string::String` with `#[derive(Reflect)]`
   = note: required for the cast from `&for<'a> fn(f32, &'a str) -> std::string::String` to `&dyn bevy_reflect::PartialReflect`
   = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `for<'a> fn(f32, &'a str) -> std::string::String` does not implement `PartialReflect` so cannot be introspected
  --> crate/src/textanim.rs:12:21
   |
12 | #[derive(Component, Reflect, Clone, PartialEq, Debug)]
   |                     ^^^^^^^ the trait `bevy_reflect::PartialReflect` is not implemented for `for<'a> fn(f32, &'a str) -> std::string::String`
   |
   = note: consider annotating `for<'a> fn(f32, &'a str) -> std::string::String` with `#[derive(Reflect)]`
   = note: required for the cast from `&mut for<'a> fn(f32, &'a str) -> std::string::String` to `&mut (dyn bevy_reflect::PartialReflect + 'static)`
   = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `for<'a> fn(f32, &'a str) -> std::string::String` does not implement `PartialReflect` so cannot be introspected
  --> crate/src/textanim.rs:12:21
   |
12 | #[derive(Component, Reflect, Clone, PartialEq, Debug)]
   |                     ^^^^^^^ the trait `bevy_reflect::PartialReflect` is not implemented for `for<'a> fn(f32, &'a str) -> std::string::String`
   |
   = note: consider annotating `for<'a> fn(f32, &'a str) -> std::string::String` with `#[derive(Reflect)]`
   = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `for<'a> fn(f32, &'a str) -> std::string::String` does not implement `TypePath` so cannot provide dynamic type path information
   --> crate/src/textanim.rs:12:21
    |
 12 | #[derive(Component, Reflect, Clone, PartialEq, Debug)]
    |                     ^^^^^^^ the trait `bevy_reflect::TypePath` is not implemented for `for<'a> fn(f32, &'a str) -> std::string::String`
    |
    = note: consider annotating `for<'a> fn(f32, &'a str) -> std::string::String` with `#[derive(Reflect)]` or `#[derive(TypePath)]`
    = note: required for `for<'a> fn(f32, &'a str) -> std::string::String` to implement `bevy_reflect::DynamicTypePath`
note: required by a bound in `to_dynamic`
   --> /Users/jankleinmann/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_reflect-0.17.2/src/reflect.rs:99:27
    |
 99 | pub trait PartialReflect: DynamicTypePath + Send + Sync
    |                           ^^^^^^^^^^^^^^^ required by this bound in `PartialReflect::to_dynamic`
...
275 |     fn to_dynamic(&self) -> Box<dyn PartialReflect> {
    |        ---------- required by a bound in this associated function
    = note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `for<'a> fn(f32, &'a str) -> std::string::String` does not implement `PartialReflect` so cannot be introspected
  --> crate/src/textanim.rs:15:15
   |
15 |     function: fn(t: f32, text: &str) -> String,
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `bevy_reflect::PartialReflect` is not implemented for `for<'a> fn(f32, &'a str) -> std::string::String`
   |
   = note: consider annotating `for<'a> fn(f32, &'a str) -> std::string::String` with `#[derive(Reflect)]`

error[E0277]: `for<'a> fn(f32, &'a str) -> std::string::String` does not implement `TypePath` so cannot provide static type path information
   --> crate/src/textanim.rs:15:15
    |
 15 |     function: fn(t: f32, text: &str) -> String,
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `bevy_reflect::TypePath` is not implemented for `for<'a> fn(f32, &'a str) -> std::string::String`
    |
    = note: consider annotating `for<'a> fn(f32, &'a str) -> std::string::String` with `#[derive(Reflect)]` or `#[derive(TypePath)]`
note: required by a bound in `reflect_clone_and_take`
   --> /Users/jankleinmann/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_reflect-0.17.2/src/reflect.rs:324:15
    |
322 |     fn reflect_clone_and_take<T: 'static>(&self) -> Result<T, ReflectCloneError>
    |        ---------------------- required by a bound in this associated function
323 |     where
324 |         Self: TypePath + Sized,
    |               ^^^^^^^^ required by this bound in `PartialReflect::reflect_clone_and_take`

error[E0277]: `for<'a> fn(f32, &'a str) -> std::string::String` does not implement `FromReflect` so cannot be created through reflection
  --> crate/src/textanim.rs:15:15
   |
15 |     function: fn(t: f32, text: &str) -> String,
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `bevy_reflect::FromReflect` is not implemented for `for<'a> fn(f32, &'a str) -> std::string::String`
   |
   = note: consider annotating `for<'a> fn(f32, &'a str) -> std::string::String` with `#[derive(Reflect)]`
```


To be honest, it doesn't even make any sense in my mind to reflect functions. This error also occurs when using #[reflect(ignore)] on the attribute.

**Comment by eugineerd** [comment]
> This error also occurs when using #[reflect(ignore)] on the attribute

You have to add `#[reflect(from_reflect = false)]` in addition to `#[reflect(ignore)]` for this to work:
```rust
#[derive(Component, Reflect, Clone, PartialEq, Debug)]
#[reflect(from_reflect = false)]
pub struct TextAnimator {
    string: String,
    #[reflect(ignore)]
    function: fn(t: f32, text: &str) -> String,
    counter: f32,
    mode: DurationMode,
}
```

**Comment by S4ndf1re** [comment]
Ahh thank you. I havn't used reflect much in the past.

**Comment by MrGVSV** [comment]
I'm going to close this one out in favor of #24151 (which tracks documenting this limitation). We don't support reflecting references and adding that functionality would require a larger conversation and design. Frankly, I'm a little surprised this worked beforehand.

If this kind of reflection is needed right away, a potential workaround is to implement the reflection traits manually (or with one of our helper macros like `impl_reflect_opaque!`).
