### PR TITLE
Implement and register Reflect (value) for CameraRenderGraph and CameraMainTextureUsages

### LINKED ISSUE #11852: Spawning scenes with cameras no longer works
## Bevy version

77c26f64ce0c1a538629a544b7020eb2d2b77466

## What you did

Exported a GLTF scene from Blender with a camera and loaded it in Bevy.

## What went wrong

The app crashed because CameraRenderGraph does not implement Reflect. This regressed in #10644.
For future reference, removing Reflect from a type that exists in a bundle used in scenes should almost never be allowed.

### PR DESCRIPTION
**Pull request by cart**
# Objective

The new render graph labels do not (and cannot) implement normal Reflect, which breaks spawning scenes with cameras (including GLTF scenes). Likewise, the new `CameraMainTextureUsages` also does not (and cannot) implement normal Reflect because it uses `wgpu::TextureUsages` under the hood.

Fixes #11852

## Solution

This implements minimal "reflect value" for `CameraRenderGraph` and `CameraMainTextureUsages` and registers the types, which satisfies our spawn logic.

Note that this _does not_ fix scene serialization for these types, which will require more significant changes. We will especially need to think about how (and if) "interned labels" will fit into the scene system. For the purposes of 0.13, I think this is the best we can do. Given that this serialization issue is prevalent throughout Bevy atm, I'm ok with adding a couple more to the pile. When we roll out the new scene system, we will be forced to solve these on a case-by-case basis.

---

## Changelog

- Implement Reflect (value) for `CameraMainTextureUsages` and `CameraRenderGraph`, and register those types.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
> Note that this does not fix scene serialization for these types, which will require more significant changes

So to be clear, this allows cameras to be spawned, but the exact values of these components are not properly preserved?

**Comment by cart** [comment]
> So to be clear, this allows cameras to be spawned, but the exact values of these components are not properly preserved?

The GLTF loader constructs a `Scene` at runtime, which uses FromReflect to construct copies on spawn, which preserves the value because these components are "reflect values" / clone-able
