### ISSUE TITLE
linking error when used with wry/tao on macOS aarch64

### ISSUE THREAD

**Issue by TarekAS** [bevyengine/bevy#11779]
## Bevy version

`0.12.1`

## Relevant system information
Chip: Apple M1 Max
OS: macOS Sonoma 14.3
Rustc: 1.75.0 (stable)
Xcode 15.2

## What you did

Consider the following minimal Rust program:
```rust
// main.rs
use bevy::prelude::*;

use tao::event_loop::EventLoop;

fn main() {
    let event_loop: EventLoop<()> = EventLoop::new();
}
```
```toml
// Cargo.toml
[package]
name = "mygame"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12.1", default-features = false, features = [
    "bevy_render",
    "dynamic_linking",
] }
tao = { version = "0.25.0", default-features = false }
wry = { version = "0.36.0" }

```

Run it on an ARM Mac and it will cause a linking error. I have tried this on 3 separate M1 Macs and it causes the same issue. I updated the OS and Xcode and that didn't solve the problem either.

## What went wrong

Project is expected to build with no issue, or an error at the compile level. Instead I get the following linking error:

```
error: linking with `cc` failed: exit status: 1
  |
  = note: env -u <redacted env print>

= note: ld: warning: ignoring duplicate libraries: '-lSystem', '-lobjc'
          ld: Undefined symbols:
            _RustObjCExceptionTryCatch, referenced from:
                objc_exception::try_no_ret::hb6c5f46d0765cd58 in libtao-b2a7c9fe6e7760b2.rlib[7](tao-b2a7c9fe6e7760b2.tao.44e5656fbb1da1ec-cgu.04.rcgu.o)
                objc_exception::try_no_ret::heb888d6999c3a1ab in libtao-b2a7c9fe6e7760b2.rlib[7](tao-b2a7c9fe6e7760b2.tao.44e5656fbb1da1ec-cgu.04.rcgu.o)
                objc_exception::try_no_ret::h467675c166da1eb2 in libcocoa-bdc083df61ae20c1.rlib[5](cocoa-bdc083df61ae20c1.cocoa.9d90b2958afad0f3-cgu.2.rcgu.o)
                objc_exception::try_no_ret::ha07b8ef05ba8efa8 in libcocoa-bdc083df61ae20c1.rlib[5](cocoa-bdc083df61ae20c1.cocoa.9d90b2958afad0f3-cgu.2.rcgu.o)
                objc_exception::try_no_ret::hd9a8b230a39d73a6 in libcocoa-bdc083df61ae20c1.rlib[5](cocoa-bdc083df61ae20c1.cocoa.9d90b2958afad0f3-cgu.2.rcgu.o)
                objc_exception::try_no_ret::he0d4cb60d8d7f302 in libcocoa-bdc083df61ae20c1.rlib[5](cocoa-bdc083df61ae20c1.cocoa.9d90b2958afad0f3-cgu.2.rcgu.o)
                objc_exception::try_no_ret::he239be2eac779649 in libcocoa-bdc083df61ae20c1.rlib[5](cocoa-bdc083df61ae20c1.cocoa.9d90b2958afad0f3-cgu.2.rcgu.o)
                ...
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Switching to Mach-O LLVM linker (aka ld64.lld) doesn't help, and returns a similar error:
```
note: ld64.lld: error: undefined symbol: RustObjCExceptionTryCatch
          >>> referenced by lib.rs:44 (/Users/redacted/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc_exception-0.1.2/src/lib.rs:44)
          >>>               /Users/redacted/wrkspc/bevy_sandbox/target/debug/deps/libtao-b2a7c9fe6e7760b2.rlib(tao-b2a7c9fe6e7760b2.tao.44e5656fbb1da1ec-cgu.04.rcgu.o):(symbol objc_exception::try_no_ret::hb6c5f46d0765cd58+0xb8)
          >>> referenced by lib.rs:44 (/Users/redacted/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc_exception-0.1.2/src/lib.rs:44)
          >>>               /Users/redacted/wrkspc/bevy_sandbox/target/debug/deps/libtao-b2a7c9fe6e7760b2.rlib(tao-b2a7c9fe6e7760b2.tao.44e5656fbb1da1ec-cgu.04.rcgu.o):(symbol objc_exception::try_no_ret::heb888d6999c3a1ab+0xa4)
          >>> referenced by lib.rs:44 (/Users/redacted/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc_exception-0.1.2/src/lib.rs:44)
          >>>               /Users/redacted/wrkspc/bevy_sandbox/target/debug/deps/libcocoa-bdc083df61ae20c1.rlib(cocoa-bdc083df61ae20c1.cocoa.9d90b2958afad0f3-cgu.2.rcgu.o):(symbol objc_exception::try_no_ret::h467675c166da1eb2+0xb8)
          >>> referenced 17 more times
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This occurs on both release and debug builds. I tried downgrading wry and tao from their latest versions (`0.36` and `0.25` respectively) but still ended up with the same variation of the error

## Additional information
I opened a parallel issue in the `wry` repo ([here]https://github.com/tauri-apps/wry/issues/1165), as I can't tell which project is actually causing this.

**Comment by BD103** [comment]
I don't think this is `wry`, because it's not referenced in the error nor imported by the program. I think this is an issue with `tao`, which raises an exception when linking to MacOS's Cocoa library. [`objc_exception`](https://lib.rs/crates/objc_exception) also appeared a few times, so it may be related to that.

I'm going to try testing this locally.

**Comment by BD103** [comment]
This is an issue with Bevy's `dynamic_linking` feature. If you turn it off, it will no longer fail to compile. This error requires `toa`, `wry`, and `bevy`. (Though only `bevy` and `toa` need to be imported.) I'm not sure what's going on, but turning off dynamic linking should fix the issue.

**Comment by TarekAS** [comment]
Turning off `dynamic_linking` does indeed solve the problem, I forgot to mention that in the OP.

**Comment by BD103** [comment]
That's very weird. I don't know enough about the libraries (+ Objective C) in question to be able to debug it myself, but let's leave the issue open.

**Comment by stewartadam** [comment]
I'm also running into this on a M3 MBP after updating from Tauri 1.6.7 -> 2.0.

Bevy 0.14.2 with dynamic linking working fine with Tauri v1.6.7, after upgrading now a very similar error is showing up:

```
  = note: ld: warning: ignoring duplicate libraries: '-lSystem', '-lc', '-lobjc'
          Undefined symbols for architecture arm64:
            "_rust_objc_sys_0_3_try_catch_exception", referenced from:
                objc2::exception::try_no_ret::h098343831220d03c in libwry-c9bb8e20141e11ee.rlib[17](wry-c9bb8e20141e11ee.wry.cb4c6861d758e4d1-cgu.14.rcgu.o)
                objc2::exception::try_no_ret::h0bc559dde5ecde4c in libwry-c9bb8e20141e11ee.rlib[17](wry-c9bb8e20141e11ee.wry.cb4c6861d758e4d1-cgu.14.rcgu.o)
                objc2::exception::try_no_ret::h11805ba2fc040271 in libwry-c9bb8e20141e11ee.rlib[17](wry-c9bb8e20141e11ee.wry.cb4c6861d758e4d1-cgu.14.rcgu.o)
                objc2::exception::try_no_ret::h191f290ef3fdd9a2 in libwry-c9bb8e20141e11ee.rlib[17](wry-c9bb8e20141e11ee.wry.cb4c6861d758e4d1-cgu.14.rcgu.o)
                objc2::exception::try_no_ret::h1b50c4034aadaddb in libwry-c9bb8e20141e11ee.rlib[17](wry-c9bb8e20141e11ee.wry.cb4c6861d758e4d1-cgu.14.rcgu.o)
                objc2::exception::try_no_ret::h22ce5d32274220da in libwry-c9bb8e20141e11ee.rlib[17](wry-c9bb8e20141e11ee.wry.cb4c6861d758e4d1-cgu.14.rcgu.o)
                objc2::exception::try_no_ret::h27efcd6461c4a597 in libwry-c9bb8e20141e11ee.rlib[17](wry-c9bb8e20141e11ee.wry.cb4c6861d758e4d1-cgu.14.rcgu.o)
                ...
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by BD103** [comment]
> `ld: symbol(s) not found for architecture arm64`

This makes me think one of the libraries doesn't support the ARM chips (M1, M3, etc.). Maybe something's Intel-only?
