### PR TITLE
Improve error message for failed entity commands

### LINKED ISSUE #19623: Observers panic when an earlier observer despawned the entity
## Bevy version

0.16.1

## What you did

```rust
use bevy::prelude::*;

fn main() -> AppExit {
    App::new()
        .add_plugins(MinimalPlugins)
        .add_systems(Startup, spawn)
        .add_systems(Update, despawn_transforms)
        .add_observer(despawn)
        .add_observer(dispatch_print)
        .add_observer(print)
        .run()
}

fn spawn(mut commands: Commands) {
    commands.spawn(Transform::default());
}

fn despawn_transforms(query: Query<Entity, With<Transform>>, mut commands: Commands) {
    for entity in query.iter() {
        commands.entity(entity).trigger(Kill);
    }
}

#[derive(Event)]
struct Kill;

#[derive(Event)]
struct Print;

fn despawn(trigger: Trigger<Kill>, mut commands: Commands) {
    commands.entity(trigger.target()).despawn();
}

fn dispatch_print(trigger: Trigger<Kill>, mut commands: Commands) {
    commands.entity(trigger.target()).trigger(Print);
}

fn print(_trigger: Trigger<Print>) {
    println!("Killed something");
}
```

## What went wrong

```
thread 'main' panicked at /home/hhh/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_ecs-0.16.1/src/error/handler.rs:141:1:
Encountered an error in command `<bevy_ecs::system::commands::entity_command::trigger<test::Print>::{{closure}} as bevy_ecs::error::command_handling::CommandWithEntity<core::result::Result<(), bevy_ecs::world::error::EntityMutableFetchError>>>::with_entity::{{closure}}`: The entity with ID 3v1 does not exist (enable `track_location` feature for more details)

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic when applying buffers for system `test::despawn_transforms`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

## Additional information

This came up organically while working on our jam submission, where the trigger is `OnDamage`. If the damage is high enough, the enemy is despawned. That means that other later running observers, like the ones playing a damage sound effect, panic. 
I would have expected the later observers to simply not run.

### LINKED ISSUE #20542: Standalone bevy_ecs tests fail to compile
## Bevy version

ed13d9b0e2572c9ce6260dd8f5fd420baf4023a3

## What you did

Attempted to run a single test in `bevy_ecs`.

The exact command run was:

```
cargo test --package bevy_ecs --lib --all-features -- world::error::tests::fixing_panicking_entity_commands --exact --show-output
```

That particular test doesn't exist on `main`: I was attempting to fix a different issue.

## What went wrong

```
error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<impl Future<Output = _>>` in the current scope
   --> crates/bevy_tasks/src/task_pool.rs:484:22
    |
483 |                   let _result = AssertUnwindSafe(executor.run(tick_forever))
    |  _______________________________-
484 | |                     .catch_unwind()
    | |                     -^^^^^^^^^^^^ method not found in `AssertUnwindSafe<impl Future<Output = _>>`
    | |_____________________|
    |

error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<{async block@crates/bevy_tasks/src/task_pool.rs:500:36: 500:41}>` in the current scope
   --> crates/bevy_tasks/src/task_pool.rs:505:62
    |
505 |                 let _result = AssertUnwindSafe(tick_forever).catch_unwind().await.is_ok();
    |                                                              ^^^^^^^^^^^^ method not found in `AssertUnwindSafe<{async block@crates/bevy_tasks/src/task_pool.rs:500:36: 500:41}>`

error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<impl Future<Output = _>>` in the current scope
   --> crates/bevy_tasks/src/task_pool.rs:525:22
    |
524 |                   let _result = AssertUnwindSafe(executor.run(tick_forever))
    |  _______________________________-
525 | |                     .catch_unwind()
    | |                     -^^^^^^^^^^^^ method not found in `AssertUnwindSafe<impl Future<Output = _>>`
    | |_____________________|
    |

error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<{async block@crates/bevy_tasks/src/task_pool.rs:540:36: 540:41}>` in the current scope
   --> crates/bevy_tasks/src/task_pool.rs:545:62
    |
545 |                 let _result = AssertUnwindSafe(tick_forever).catch_unwind().await.is_ok();
    |                                                              ^^^^^^^^^^^^ method not found in `AssertUnwindSafe<{async block@crates/bevy_tasks/src/task_pool.rs:540:36: 540:41}>`

error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<Fut>` in the current scope
   --> crates/bevy_tasks/src/task_pool.rs:649:40
    |
649 |             .spawn(AssertUnwindSafe(f).catch_unwind())
    |                                        ^^^^^^^^^^^^ method not found in `AssertUnwindSafe<Fut>`

error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<Fut>` in the current scope
   --> crates/bevy_tasks/src/task_pool.rs:665:40
    |
665 |             .spawn(AssertUnwindSafe(f).catch_unwind())
    |                                        ^^^^^^^^^^^^ method not found in `AssertUnwindSafe<Fut>`

error[E0599]: no method named `catch_unwind` found for struct `AssertUnwindSafe<Fut>` in the current scope
   --> crates/bevy_tasks/src/task_pool.rs:682:40
    |
682 |             .spawn(AssertUnwindSafe(f).catch_unwind())
    |                                        ^^^^^^^^^^^^ method not found in `AssertUnwindSafe<Fut>`

error[E0432]: unresolved import `__automatic_type_registration_impl`
   --> crates/bevy_reflect/src/lib.rs:820:17
    |
820 |         pub use __automatic_type_registration_impl::*;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `__automatic_type_registration_impl`
    |
    = help: if you wanted to use a crate named `__automatic_type_registration_impl`, use `cargo add __automatic_type_registration_impl` to add it to your `Cargo.toml`
```

## Additional information

Likely introduced by #15030.

### PR DESCRIPTION
**Pull request by alice-i-cecile**
# Objective

- If an entity command is sent targeting a despawned entity, that command will error, and then panic by default.
- This occurs even if the entity exists at the time the command was sent.
- This can cause surprising panics when working with observers that depend on each other, especially when using entity events that cause entities to be despawned.
- Closes #19623.

## Solution

As outlined in #19623, this behavior isn't exactly a bug, although it is surprising.

When you attempt to trigger an observer for an entity that doesn't exist, Bevy should give you some indication that something has gone wrong!

The standard mechanism we have for doing so is to return an error in the command, which is passed to the default error handler. By default, this panics, reproducing the problem reported in #19623.

Unfortunately, the error reporting was so bad that neither the OP nor the contributors could quickly isolate the problem and tell them what they should be doing differently.

The actual solution is both standard to the rest of Bevy and quite simple: just queue the command in a way that makes the error not panic. We should explain that!

I've added commentary to that effect on both `EntityCommands::trigger/trigger_targets` and the error message returned.

## Testing

I've added a new test demonstrating the fix for this failure mode. Swapping that test to plain `.trigger` fixes the problem.

### CODE REVIEW

**Review by ChristopherBiscardi — APPROVED** [review]
makes sense to me. I like how `queue_silenced` makes it clear when reading the code that this could be ignored.

File: crates/bevy_ecs/src/world/error.rs [hunk 1]
```diff
@@ -50,7 +50,11 @@ pub enum EntityComponentError {
 #[derive(thiserror::Error, Debug, Clone, Copy, PartialEq, Eq)]
 pub enum EntityMutableFetchError {
     /// The entity with the given ID does not exist.
-    #[error(transparent)]
+    #[error(
+        "{0} does not exist.\n
```
Comment (JaySpruce) [inline crates/bevy_ecs/src/world/error.rs]: I believe this will print wrong, because `EntityDoesNotExistError` also contains the "does not exist" part.
```suggestion
        "{0}.\n
```

File: crates/bevy_ecs/src/world/error.rs [hunk 2]
```diff
@@ -70,3 +74,50 @@ pub enum ResourceFetchError {
...
+            // When using a simple .trigger() here, this panics because the entity has already been despawned.
+            // Instead, we need to use `.queue_handled` or `.queue_silenced` to avoid the panic.
+            commands
+                .entity(on.target())
+                .queue_silenced(trigger(FollowupEvent));
+        }
+
+        let mut world = World::new();
+        // At the time of creation,
+        // this test would pass if the order of these statements is swapped
```
Comment (JaySpruce) [inline crates/bevy_ecs/src/world/error.rs]: Outdated comment (still true but kind of confusing now)

File: crates/bevy_ecs/src/system/commands/mod.rs [hunk 3]
```diff
@@ -1094,6 +1094,12 @@ impl<'w, 's> Commands<'w, 's> {
     /// Sends an [`EntityEvent`] for the given targets.
     ///
     /// This will run any [`Observer`] of the given [`EntityEvent`] watching those targets.
+    ///
+    /// If the entity that this command targets does not exist when the command is applied,
+    /// the command will fail, possibly causing it to panic based on the default error handler set.
```
Comment (JaySpruce) [inline crates/bevy_ecs/src/system/commands/mod.rs]: Maybe link to the default error handler, or the error module docs?
```suggestion
    /// the command will fail, possibly causing it to panic based on the default [error handler](crate::error) set.
```

File: crates/bevy_ecs/src/system/commands/mod.rs [hunk 4]
```diff
@@ -1094,6 +1094,12 @@ impl<'w, 's> Commands<'w, 's> {
...
+    /// To queue this command with a handler, use [`EntityCommands::queue_handled`]
```
Comment (JaySpruce) [inline crates/bevy_ecs/src/system/commands/mod.rs]: Nit: `queue` still queues with a handler, just not one you can specify per command :P

```suggestion
    /// To queue this command with a specific handler, use [`EntityCommands::queue_handled`]
```

Comment (JaySpruce) [reply crates/bevy_ecs/src/system/commands/mod.rs]: Also, maybe separate paragraphs

```suggestion
    ///
    /// To queue this command with a handler, use [`EntityCommands::queue_handled`]
```

**Review by janhohenheim — APPROVED** [review]
IME the actual "fix" for the error I've seen in practice is to use a `Despawn` component and then despawn all tagged entities in `PostUpdate, before TransformPropagation`, as that fixes all related issues too, like `insert` and `remove` erroring when the entity is despawned and then panicking your app by default.

In that sense, I think the suggested workaround used in the error is not entirely reflective of reality. Still approving because this is better than the status quo.

**Comment by alice-i-cecile** [comment]
Yeah, I think that there's broader questions to answer about our default error handling solution. @NthTensor mentioned that we may want to tag errors by their severity, which I like. But that's a larger design question, and well beyond the scope of what I want to tackle in the waning hours of 0.17.

**Comment by NthTensor** [comment]
We should probably get a ticket up for error severity hints in the 0.18 milestone. I thought I wrote one of those, maybe I'm crazy.
